README.md
Having this in a single place will let us easily reference it from all other
repos without having to duplicate material. It also serves to document this repo
locally so that folks who come across it directly know what purpose it serves
and who to work with JanusGraph.
This brings the content over from [`JanusGraph/janusgraph/CONTRIBUTING.md`](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).
=> Describe CLA signature process.

README.md
Now that the CLA signing instructions are in the same repo as the docs
themselves, we can use the shorter and simpler relative links.
=> Use relative links for CLA docs.

CLA_SIGNERS.yaml
=> Add Mathias Bogaert via offline signed ICLA.

CLA_SIGNERS.yaml
Per https://github.com/web-flow:
> "This account is the Git committer for all web commits (merge/revert/edit/etc...) made on GitHub.com."
This is a special GitHub account that needs to be whitelisted to enable
actions taken by contributors via the GitHub web UI to be processed as
having cleared the CLA verification. All Git commits have an "author" and a
"committer" and we verify that both appear in this file.
In the case of users making changes via the GitHub web UI, the "author" is
the person who made the change, but the "committer" rather than being the
same person is actually "web-flow" and unless it's whitelisted as done here,
the overall PR will fail the CLA verification check.
We avoid adding `@web-flow` to the `people` list (above) because:
* there isn't a real person behind this …
=> Add GitHub's @web-flow bot to the whitelist.

CLA_SIGNERS.yaml
Creates a canonical ordering of signers, rather than being listed in order of signature.
=> Alphabetize individual signers by name.

CLA_SIGNERS.yaml
This should address the CLA issue in https://github.com/JanusGraph/janusgraph/pull/188 by adding an additional email address for @twilmes.
=> Add alternate email address for @twilmes

CLA_SIGNERS.yaml
Added per email from Amazon CCLA administrators.
Welcome to JanusGraph, @mrodaitis!
=> Extend Amazon CCLA to cover @mrodaitis

CLA_SIGNERS.yaml
When performing a merge via GitHub's web UI, the commit uses the user's default
email address in their profile, which may not be the same one as what is in
their CLA, which causes a future branch merge (second-order merge) to fail with
a `cla: no` label since the commit author is no longer on the CLA.
This change addresses the situation by adding alternate email addresses for the
users affected by this recently in https://github.com/JanusGraph/janusgraph/pull/393
=> Add default emails for @amcp and @jerryjch

CLA_SIGNERS.yaml
@myhrvold, did I guess correctly that you used the GitHub web UI to make your change in https://github.com/JanusGraph/legal/pull/41?
If so, I propose adding your email address here to make that workflow easier; sounds like we'll be adding this for several folks, and might potentially need to make this into a special case to handle the general problem better for everyone automatically.
=> Add alternate email address for @myhrvold

CLA_SIGNERS.yaml
Exact name and email in the CLA must match that of the patch:
https://github.com/JanusGraph/legal/pull/41.patch
or the CLA bot is not happy and marks the commit, and hence the PR, as
non-conformant to the signed CLAs on file.
Longer term, the more elegant way to handle this in the `CLA_SIGNERS.yaml` file
will be to add alternate names and email addresses for everyone to make this
process easier.
This ought to fix the CLA tag on PR #41.
=> Fix @myhrvold's name to match GitHub account

README.md
Since we moved out the Git guide to setting up your repository to match the CLA
to the main repo in the `CONTRIBUTING.md` file vs. the `README.md` file in the legal
repo, update the text and URL to point to the correct location.
=> Update link to point to CONTRIBUTING.md guide

CLA_SIGNERS.yaml
Since we don't have complete information for every person on the list, they are
added but commented out. One person has complete information on file, so he is
added to enable verification of his PRs which are already on GitHub, waiting for
review.
@ngrigoriev and Newforma team – welcome to the JanusGraph project!
=> Add Newforma per offline-signed CCLA.

CLA_SIGNERS.yaml
Now that https://github.com/JanusGraph/janusgraph/pull/671 has been
updated to use @newforma.com email address, we can remove the
@gmail.com address from the CCLA for consistency.
FYI, @ngrigoriev and @pfilion.
=> Update Nikolai Grigoriev's email address.

CLA_SIGNERS.yaml
Addition per email request from Sebastian Good (@sebastiang),
CCLA manager for Expero.
Welcome to the JanusGraph project, @chrislbs!
=> Add Chris Pounds to Expero CCLA.

CLA_SIGNERS.yaml
Also, marked @haikalpribadi as CLA manager. Both changes per email
request from Domenico and Haikal.
Welcome to the JanusGraph project, @pluraliseseverythings!
Note: this PR is a subset of https://github.com/JanusGraph/legal/pull/68 such that it can be marked with `[cla: yes]` so that there are no force-submits of non-CLA-approved material.
=> Add Domenico Corapi to the GRAKN.AI CCLA

CLA_SIGNERS.yaml
Fixes email address added incorrectly by @mbrukman in
https://github.com/JanusGraph/legal/pull/70 .
This will enable submitting https://github.com/JanusGraph/legal/pull/71
once other issues with the commit (usage of full name) are addressed.
=> Fix email address For Domenico Corapi.

CLA_SIGNERS.yaml
This is evident in merges from 0.2 branch to master, e.g., via
https://github.com/JanusGraph/janusgraph/pull/724
=> Add default name used for merge commits.

CLA_SIGNERS.yaml
We have received a signed CCLA from this startup, but they prefer to
stay private and unnamed as they are still in stealth mode.
@krlohnes, please review.
@pluradj, FYI.
=> Keith Lohnes left IBM and joined a startup.

CLA_SIGNERS.yaml
Adam Holley is no longer at IBM as per:
https://www.linkedin.com/in/holleyism/
FYI, @holleyism: if you'd like to contribute to JanusGraph, please ask your new employer to sign a CCLA with JanusGraph and list you as a contributor.
=> Remove Adam Holley from IBM CCLA

CLA_SIGNERS.yaml
Namely, the following folks left GRAKN.AI and will be removed:
* Borislav Iordanov (@bolerio)
* Domenico Corapi (@pluraliseseverythings)
* Sheldon Hall (@sheldonkhall)
Folks, if you would like to continue to contribute to JanusGraph (and we hope you do!), please submit:
* a new ICLA — if you will be contributing as an individual, i.e., no company can claim ownership of your contributions, or
* a new CCLA — if you will be contributing as an employee of another company
Thank you for your contributions!
=> Remove folks who left GRAKN.AI from CCLA

CLA_SIGNERS.yaml
This is a follow-up to PR #82; @changzhihua prefers to use his legal name "Zhihua Chang".
The previous PR was merged before I saw an update from @changzhihua requesting this change.
=> Update Bruce Chang's listed name per request.

.travis.yml
Use `group: travis_latest` instead of `dist: trusty` to pick up the
latest Travis CI image changes. The new default is `group: travis_lts`
which is equivalent to the now-deprecated `dist: trusty`.
More info in this blog post:
https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
The same change was previously made in the main repo:
https://github.com/JanusGraph/janusgraph/pull/824
=> Switch to Travis CI latest image versions.

CLA_SIGNERS.yaml
Welcome back to the JanusGraph project, @holleyism!
=> Add Adam Holley per offline-signed ICLA.

CLA_SIGNERS.yaml
Per https://www.linkedin.com/in/ptgoetz/ he now works at EPAM and hence
cannot be covered by the Hortonworks CCLA.
@ptgoetz: if you'd like to contribute to JanusGraph going forward, please submit a new CLA — we'd love to have you continue to be involved in JanusGraph!
/cc: @alanfgates, @simonellistonball (FYI)
=> Remove P. Taylor Goetz from Hortonworks CCLA.

CLA_SIGNERS.yaml
Welcome to the JanusGraph project, @prithvinambiar! We look forward to your contributions.
=> Add Prithvi Nambiar per offline-signed ICLA.

CLA_SIGNERS.yaml
Alex relocated from Japan to the US; update email address accordingly.
This change replaces https://github.com/JanusGraph/legal/pull/106 due to
the CLA issues that PR was affected by.
=> Update email address for Alexander Patrikalakis

CLA_SIGNERS.yaml
=> Add Oleksandr Porunov per offline-signed ICLA

CLA_SIGNERS.yaml
This address was used for some of the past (and current) PRs and serves
to document that @amcp committed to the project with multiple email
addresses, all of which are valid under the CCLA.
Fixes https://github.com/JanusGraph/legal/issues/105
=> Add Alexander Patrikalakis' Japan email address.

CLA_SIGNERS.yaml
Welcome to the JanusGraph project, @polpo1980!
@nidmgh, best of luck in your new role! Please sign a new CCLA if you'd like to contribute to JanusGraph with your new company.
---
Since Demai Ni left Huawei, there are no authorized contributors left on
the Huawei CCLA nor is there a CLA Manager. This change replaces Demai
Ni with Minqi Zhou to manage the Huawei CCLA going forward.
Fixes #121.
=> Update Huawei CLA Manager.

new-repo/APACHE-2.0.txt, new-repo/LICENSE.txt
This line is not supposed to be a specific copyright holder or year;
it's a template line, and should have been transferred as-is from the
Apache 2.0 license, which can be found at
https://www.apache.org/licenses/LICENSE-2.0.txt
=> Fix Apache license to use proper template.

CLA_SIGNERS.yaml
This change also moves Dmitry Kovalev's earlier ICLA entry to be
included under the GS CCLA.
Welcome to the JanusGraph project,  @gg4real, @dk-github, @rmj-github, @nathsachindra and @codemonk5! We look forward to your contributions.
=> Add Goldman Sachs team via offline-signed CCLA.

Makefile, cla_signers.py, cla_signers_test.py
Outputs a clear message to show which field(s) are empty/unspecified to
allow easily tracking down an error in the config (found while
attempting to make a change and forgetting to set a field).
This change also adds some basic tests to enable making safer changes to
the validation logic in the future, as adding a test is now as simple as
adding a new test method.
=> Add graceful support for handling empty fields

cla_signers.py, cla_signers_test.py
Previously, errors in the 'people' and 'bots' sections were silently ignored
because the return value from `ValidateAccounts()` were dropped. Incidentally,
it made it not possible to write concise test cases which used only 'people' or
'bots' section but without an invalid 'companies' section.
Also, made all sections ('people', 'bots', and 'companies') optional as a
particular config can contain any subset of these sections.
Finally, added handling of empty entries (accounts) in a section with proper
error reporting.
=> Handle errors in 'people' and 'bots' sections

cla_signers.py, cla_signers_test.py
Instead of directly outputting errors to stderr, simply return a tuple of
(valid, errors) and let the caller handle how to output it.
This also cleans up the error reporting when running tests, and will allow us to
test error messages if we choose to do so in the future.
=> Convert code to functional style

CLA_SIGNERS.yaml
Note: since Jerry Chen He moved from IBM to eBay so his entry has moved to the
new company with an updated email address, but his @apache.org email is retained
to enable GitHub web-UI-based merging to continue as previously.
/cc: @jerryjch, @brianhaslam
=> Add eBay per offline-signed CCLA.

CLA_SIGNERS.yaml
As we are moving towards using The Linux Foundation CLA tool, we are starting 
with removing users from being managed by our own @janusgraph-bot and instead
managed externally by the LF CLA tool. This is the first step in that
direction.
=> Remove GitHub's web-flow bot from CLA

CLA_SIGNERS.yaml
=> Removed Chris Hupman as IBM contributor

CLA_SIGNERS.yaml
https://archpaper.com/2018/02/flux-to-shut-down/
FYI, @FluxMcarrier — if you'd like to continue contributing to JanusGraph, please sign an ICLA or ask your current employer to sign a CCLA via the new electronic LF EasyCLA process: https://lfcla.com/
=> Remove Flux CCLA as the company was shut down

CLA_SIGNERS.yaml
Hortonworks merged with Cloudera, but the name of the combined company
is "Cloudera" so Hortonworks (the brand name) has been retired.
Additionally, https://hortonworks.com redirects to https://cloudera.com,
which also suggests that the old name is no longer being used.
Thus, we need to remove the Hortonworks CCLA as it is no longer in
force, and if folks from the combined Cloudera/Hortonworks entity want
to contribute to JanusGraph, they will need to have Cloudera sign a new
CCLA, which might as well be done via the new electronic LF EasyCLA
process rather than the old-style process.
---
/cc: @alanfgates, @simonellistonball (FYI)
=> Remove Hortonworks CCLA as it merged with Cloudera

CLA_SIGNERS.yaml
This developer has already signed the LF EasyCLA, as can be evidenced in
https://github.com/JanusGraph/janusgraph/pull/1973
Merging this PR will switch the @janusgraph-bot managed CLA labels from
`[cla: yes]` to `[cla: external]` and we will rely on EasyCLA check
going forward for this developer's PRs.
---
/cc: @VladimirBogomolov (FYI, no action needed, since you've already signed the LF EasyCLA)
=> Remove VladimirBogomolov from offline ICLA

CLA_SIGNERS.yaml
We are migrating from the offline CLA process to the electronic LF
EasyCLA process, and @mad has already signed the LF EasyCLA, as can be
seen on: https://github.com/JanusGraph/janusgraph/pull/1977
Merging this PR will switch the @janusgraph-bot managed CLA labels from
`[cla: yes]` to `[cla: external]` and we will rely on EasyCLA check
going forward for this developer's PRs.
=> Remove @mad from the offline ICLA

CLA_SIGNERS.yaml
@amcp — if you're interested in contributing to JanusGraph, please ask your new employer to sign the CCLA via the new electronic LF CLA process: https://corporate.lfcla.com .
/cc: @hyandell and @brandis (FYI) since we're removing one of your ex-employees from your CCLA. Also, I'll be in touch with you separately by email about migrating your CCLA to the new electronic LF CLA process.
=> Remove @amcp from Amazon CCLA as he changed jobs

CLA_SIGNERS.yaml
This user has already signed the LF EasyCLA as evidenced in many recent PRs, so
we can switch to LF EasyCLA going forward.
=> Migrate @porunov from offline ICLA to LF EasyCLA
