JanusGraph/legal

.travis.yml

Add Travis CI config to validate YAML.

---

Makefile

No need to create directory; exists by default.

---

CLA_SIGNERS.yaml

Add Robert Dale via offline signed ICLA.

---

CLA_SIGNERS.yaml

Added Dylan Bethune-Waddell via signed ICLA.

---

CLA_SIGNERS.yaml

/cc: @sebastiang, @twilmes, @chadthehuff, @bechbd, @michaeldownie-expero, @joshpci

Added Expero folks via offline signed CCLA.

---

CLA_SIGNERS.yaml

/cc: @haikalpribadi, @bolerio, @fppt, @aelred, @sheldonkhall, @duckofyork, @kasper-piskorski (FYI)

Added GRAKN.AI folks via offline signed CCLA.

---

cla_signers.py

Add basic YAML field name validations.

---

CLA_SIGNERS.yaml

/cc: @ptgoetz, @alanfgates (FYI)

Added Hortonworks folks via offline signed CCLA.

---

CLA_SIGNERS.yaml

/cc: @pluradj, @jerryjch, @smcquillan, @tanping (FYI)

Added IBM folks via offline signed CCLA.

---

CLA_SIGNERS.yaml
cla_signers.py

/cc: @mbrukman, @lindsayismith, @mgiambalvo, @rameshdharan, @garye (FYI)

Added Google folks via offline signed CCLA.

---

CLA_SIGNERS.yaml

Added sjudeng via offline signed ICLA.

---

CLA_SIGNERS.yaml

/cc: @aspyker, @burakbacioglu, @boney9, @majinwala, @v1r3n, @vikramsingh2104, @ipapapa, @shailesh33, @vinaykumarchella, @arunagrawal84, @mfiguiere

Added Netflix folks via offline signed CCLA.

---

CLA_SIGNERS.yaml

Added Amazon contributor via offline signed CCLA.

---

CLA_SIGNERS.yaml

Add Rafael Fernandes via offline signed ICLA.

---

CLA_SIGNERS.yaml

Add Den Kovalevsky via offline signed ICLA.

---

cla_signers.py

Adds validation for the change introduced in PR #21.

Validate the `bots` config section.

---

CLA_SIGNERS.yaml

cc: @pkendall64, @samant-orionhealth
Welcome to the project!

Add Orchestral Developments via offline CCLA.

---

CLA_SIGNERS.yaml

cc: @kottmann
Welcome to the project!

Add Joern Kottmann via offline signed ICLA.

---

CLA_SIGNERS.yaml

Additional IBM contributors

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @boliza!

Add folks from Monogram via offline signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @myhrvold, @dbolcioni, @countrodrigo, @kedarmhaswade, @chrilusf, @tunaygur, @suganyar, @vigneshgg!

Add folks from Uber via offline signed CCLA.

---

CLA_SIGNERS.yaml

Updated GitHub id per @myhrvold.
Welcome to the JanusGraph project, @chrislusf!

Fix GitHub id for Chris Lu of Uber.

---

CLA_SIGNERS.yaml

Additional IBM contributor

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @JoelSanchez!

Add JoelSanchez via offline signed ICLA.

---

CLA_SIGNERS.yaml

Welcome to JanusGraph, @xiangqiao123!

Added Qiao Xiang via offline signed ICLA.

---

CLA_SIGNERS.yaml

Welcome to JanusGraph, @davidclement90!

Add David Clement via offline signed ICLA.

---

CLA_SIGNERS.yaml

FYI, @tunaygur, this will fix the CLA verification on your PR https://github.com/JanusGraph/janusgraph/pull/260

Fix Tunay Gur's email address per his PR.

---

CLA_SIGNERS.yaml

Added one IBM contributor, removed two IBM contributors

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @mikesager!

Add Mike Sager via offline signed ICLA.

---

CLA_SIGNERS.yaml

@pluradj, here's the fix as per discussion in https://github.com/JanusGraph/janusgraph/pull/377#issuecomment-312963586

Add alternate email address for @pluradj

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @mpderbec, @sharpau, @deafgreatdane, @haroldhues, @cilvedson, @dakkanner, @dustin-johnson, @jrust, @totallyna, @sfurholm, and @srosenthal!
We look forward to your contributions.

Add Seeq contributors via offline signed CCLA.

---

CLA_SIGNERS.yaml

Welcome @skkolli to the JanusGraph project!

Add Centrifuge per offline signed CCLA

---

Makefile
cla_signers.py

A simple way to see the numbers of individuals and companies who are signed up
to make contributions to JanusGraph. Can be run easly via `make stats`.

Add command to print CLA signer statistics.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @igorbernstein2!

Added Igor Bernstein to existing Google CCLA

---

Makefile

Update the target from `yaml-check` to `validate` as that's the actual command
in the Python script.

Change Makefile target to `validate` for clarity

---

CLA_SIGNERS.yaml

Added a new IBM contributor

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @nidmgh! We look forward to your contributions.

Add Huawei per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @ngocson2vn!

Add Son Nguyen per offline-signed ICLA.

---

CLA_SIGNERS.yaml

FYI, @aspyker ­— apologies for leaving off this comment when we first processed your CCLA.

Mark Andrew Spyker as CLA Manager.

---

.travis.yml
README.md

* adds copyright header comment to `.travis.yml`
* adds Travis CI badge to `README.md`

Travis CI updates

---

CLA_SIGNERS.yaml

Per request from Andrew Spyker (@aspyker@) in another PR:
https://github.com/JanusGraph/legal/pull/63#issuecomment-339704603

Update Andrew Spyker's email address.

---

CLA_SIGNERS.yaml

Added 1 new IBM contributor

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @FluxMcarrier and Flux team!

Add Flux folks per offline-signed CCLA.

---

APACHE-2.0.txt
CC-BY-4.0.txt
LICENSE.txt
README.md

Also adds a clarification to `README.md` with the pointers to the other files.

Add license files from main repo for consistency.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @sduskis!

Add Solomon Duskis (@sduskis) to Google CCLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @Lakedaemon!

Add Olivier Binda via offline signed ICLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @changzhihua!

Added Bruce Chang per offline signed ICLA.

---

CLA_SIGNERS.yaml

Remove 1 IBM contributor

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @fbalicchia!

Add Filippo Balicchia per offline signed ICLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @FlorianHockmann, @farodin91, @kdrblkbs, and @Schums! We look forward to your contributions.

Add G DATA folks per offline signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @fxue!

Add Fei Xue to Google CCLA.

---

CLA_SIGNERS.yaml

Add new IBM contributor, and add another name/email combo for dpitera

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @sheymann, @davidrapin, @francescoinfante, and @Diachk!

Add Linkurious folks per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @pankajydv, @rahul38888, @anuraganand789, @anamika121, and @himgang!

Add Times Internet per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome @YevIgn to the JanusGraph project!

Add Evgeniy Ignatiev per offline-signed ICLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @sthielo, @BeatSager, and @jolipp!
We look forward to your contributions.

Add Altoo AG per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @woncius, @Icaruszzc, and @imbajin!
We look forward to your contributions.

Add Qihoo360 folks per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome @lbritton and @yxzhou from @VMware to the JanusGraph project!
We look forward to your contributions.

Add VMware folks per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Add new IBM contributor

---

CLA_SIGNERS.yaml

Signed-off-by: Haikal Pribadi <haikal@grakn.ai>

Updating CLA Signers from GRAKN.AI

---

CLA_SIGNERS.yaml

Signed-off-by: Florian Hockmann <fh@florian-hockmann.de>

Remove G DATA contributor

---

CLA_SIGNERS.yaml

Additional GitHub name/email for chupman

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @paul-k-civitas!
This should address the CLA issue in https://github.com/JanusGraph/janusgraph/pull/1199

Add Civitas Learning per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @tonit!

Add Rebaze based on offline-signed CCLA.

---

CLA_SIGNERS.yaml

Updated IBM contributors

---

CLA_SIGNERS.yaml

Add Raul Guo per offline-signed ICLA

---

CLA_SIGNERS.yaml

Add Antriksh Shah per offline-signed ICLA

---

README.md
new-repo/APACHE-2.0.txt
new-repo/CC-BY-4.0.txt
new-repo/LICENSE.txt
new-repo/README.md

Also added a starter kit of the initial files, and how to ensure that
automated CLA verification takes place for all new repos.
Fixes #112.

Added instructions for creating a new repo.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @dk-github!

Add Dmitry Kovalev per offline-signed ICLA.

---

CLA_SIGNERS.yaml

FYI, @paul-k-civitas and @ppadovani.

Add contact for Civitas Learning CLA manager.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @mbbeaubi!

Add Informatica per offline-signed CCLA.

---

CLA_SIGNERS.yaml

Add Pavel Ershov per offline-signed ICLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @wangzheng90! We look forward to your contributions.

Add Zheng Wang per offline-signed ICLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @pontusvision! We look forward to your contributions.

Add Pontus Networks per offline-signed CCLA

---

CLA_SIGNERS.yaml

Added Vladimir Bogomolov per offline-signed ICLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @fufler! We look forward to your contributions.

Add Alexey Ermakov per offline-signed ICLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @ph1lm and @pheller from Comcast! We look forward to your contributions.

Add Comcast per offline-signed CCLA

---

.travis.yml
Makefile
cla_signers.py
requirements.txt

I wanted to make it so the unit tests would run even if the lint failed so I separated them into different stages. 
Signed-off-by: Chris Hupman <chupman@us.ibm.com>

Adding lint check to testing

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @avikivity! We look forward to your contributions.

Add ScyllaDB per offline-signed CCLA

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @bramford! We look forward to your contributions.

Add Bramford Horton per offline-signed ICLA.

---

CLA_SIGNERS.yaml

Welcome to the JanusGraph project, @darwinyip! We look forward to your contributions.
This should address the CLA issue in https://github.com/JanusGraph/janusgraph/pull/1516 and any other outstanding PRs.

Add Darwin Yip per offline-signed ICLA.

---

CLA_SIGNERS.yaml

Signed-off-by: Jan Jansen <jan.jansen@gdata.de>

Remove gdata from offline sign

---

CLA_SIGNERS.yaml

For detailed background and discussion, see comments:
* https://github.com/JanusGraph/janusgraph/pull/2173#issuecomment-668057754
* https://github.com/JanusGraph/janusgraph/pull/2173#issuecomment-668063275
@YevIgn, please review and confirm this is correct.

Adding new spelling of @YevIgn's name, per request.
